name: GenDocs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add DSharpPlus SlimGet
      run: dotnet nuget add source https://nuget.emzi0767.com/api/v3/index.json -n DSharpPlusSlimGet
    - name: Build solution
      run: |
        dotnet build --verbosity:m -p:Configuration=Release
    - name: Create MD
      run: |
        mkdir .\publish
        .\MDExtractor\bin\Release\netcoreapp3.1\MDExtractor.exe .\publish\index.md
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.5.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: publish # The folder the action should deploy.
